Fixed tag uniqueness bug & Replaced Annotation ID creation method
Previous tag implementation resulted in:
"tag_set.add(entry)
TypeError: unhashable type: 'collections.OrderedDict'"

This was fixed by removing the set structure and replacing it with DB
checks.

Modified the method of obtaining annotation_id so that it generates a
URI in accordance with the W3C annotation specification.